<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="29079" started-at="2020-11-05T12:03:16Z" finished-at="2020-11-05T12:03:45Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="29079" started-at="2020-11-05T12:03:16Z" finished-at="2020-11-05T12:03:45Z">
      <class name="com.tests.TestSearchProduct">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.tests.TestSearchProduct@29774679]" name="setUp" is-config="true" duration-ms="10757" started-at="2020-11-05T12:03:05Z" finished-at="2020-11-05T12:03:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="profileSetup()[pri:0, instance:com.tests.TestSearchProduct@29774679]" name="profileSetup" is-config="true" duration-ms="0" started-at="2020-11-05T12:03:16Z" finished-at="2020-11-05T12:03:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- profileSetup -->
        <test-method status="PASS" signature="searchProduct()[pri:0, instance:com.tests.TestSearchProduct@29774679]" name="searchProduct" duration-ms="11049" started-at="2020-11-05T12:03:16Z" finished-at="2020-11-05T12:03:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchProduct -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.tests.TestSearchProduct@29774679]" name="afterMethod" is-config="true" duration-ms="2" started-at="2020-11-05T12:03:27Z" finished-at="2020-11-05T12:03:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="testTitle()[pri:0, instance:com.tests.TestSearchProduct@29774679]" name="testTitle" duration-ms="18007" started-at="2020-11-05T12:03:27Z" finished-at="2020-11-05T12:03:45Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Amazon.es: compra online de electr칩nica, libros, deporte, hogar, moda y mucho m치s.> but was:<Amazon>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Amazon.es: compra online de electr칩nica, libros, deporte, hogar, moda y mucho m치s.> but was:<Amazon>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
at com.tests.TestSearchProduct.testTitle(TestSearchProduct.java:95)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTitle -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.tests.TestSearchProduct@29774679]" name="afterMethod" is-config="true" duration-ms="0" started-at="2020-11-05T12:03:45Z" finished-at="2020-11-05T12:03:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="quit()[pri:0, instance:com.tests.TestSearchProduct@29774679]" name="quit" is-config="true" duration-ms="1280" started-at="2020-11-05T12:03:45Z" finished-at="2020-11-05T12:03:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- com.tests.TestSearchProduct -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
